services:
  db:
    image: pgvector/pgvector:pg16
    container_name: sorcerer_db
    environment:
      POSTGRES_DB: sorcerer 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Increase shared memory limit for parallel HNSW index builds
    shm_size: '1gb'

volumes:
  postgres_data: 